import React, { useMemo, useState } from 'react';
import { Model } from 'survey-core';
import { Survey } from 'survey-react-ui';
import 'survey-core/survey-core.min.css';
import { Button } from 'primereact/button';
import { Dialog } from 'primereact/dialog';
import { EmbedPDF } from './EmbedPDF';
import jsPDF from 'jspdf';

interface DynamicLetterFormProps {
    schema: any;
    onSubmit: (data: any) => void;
    // Optional custom PDF generator. If not provided, a default one creates a letter based on data.
    generatePdfPreview?: (data: any) => Promise<string>;
}

export const DynamicLetterForm: React.FC<DynamicLetterFormProps> = ({ schema, onSubmit, generatePdfPreview }) => {
    const [previewVisible, setPreviewVisible] = useState(false);
    const [pdfBase64, setPdfBase64] = useState<string | null>(null);

    const survey = useMemo(() => {
        const s = new Model(schema);
        s.showNavigationButtons = false; // We use our own custom buttons
        return s;
    }, [schema]);

    const handlePreview = async () => {
        // We can validate before preview if we want, but let's allow preview of partial data too
        const data = survey.data;
        let base64 = "";
        
        if (generatePdfPreview) {
            base64 = await generatePdfPreview(data);
        } else {
            // Default PDF generation using jsPDF
            const doc = new jsPDF();
            doc.setFont('helvetica');
            
            // Letterhead
            doc.setFontSize(20);
            doc.setTextColor(33, 33, 33);
            doc.text("Official Correspondence", 20, 30);
            
            doc.setFontSize(10);
            doc.setTextColor(100, 100, 100);
            doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 40);
            
            // Content
            doc.setFontSize(12);
            doc.setTextColor(50, 50, 50);
            let y = 60;
            
            for (const [key, value] of Object.entries(data)) {
                doc.setFont('helvetica', 'bold');
                doc.text(`${key}:`, 20, y);
                doc.setFont('helvetica', 'normal');
                
                const valueStr = String(value);
                const lines = doc.splitTextToSize(valueStr, 120);
                doc.text(lines, 60, y);
                
                y += 10 * lines.length + 5;
                
                if (y > 270) {
                    doc.addPage();
                    y = 20;
                }
            }
            
            // Signature
            doc.setFont('helvetica', 'italic');
            doc.text("Generated by Case Management System", 20, y + 20);
            
            const docDataUrl = doc.output("datauristring");
            base64 = docDataUrl.split(',')[1];
        }
        
        setPdfBase64(base64);
        setPreviewVisible(true);
    };

    const handleSubmit = () => {
        if (survey.validate()) {
            onSubmit(survey.data);
        }
    };

    return (
        <div className="flex flex-column gap-0">
            <div className="surface-card border-round-xl shadow-1 border-1 border-200 overflow-hidden">
                <div className="p-2">
                    <Survey model={survey} />
                    {/* Add a tiny bit of CSS to make SurveyJS look more like PrimeFlex */}
                    <style>{`
                        .sd-root-modern { padding: 0; background: transparent; }
                        .sd-container-modern { padding: 0 !important; }
                        .sd-body { padding: 1rem !important; }
                    `}</style>
                </div>
                <div className="p-4 border-top-1 border-200 flex justify-content-end gap-3 surface-50">
                    <Button label="Preview Letter" icon="pi pi-eye" outlined severity="secondary" onClick={handlePreview} />
                    <Button label="Submit Document" icon="pi pi-send" onClick={handleSubmit} />
                </div>
            </div>

            <Dialog 
                header={
                    <div className="flex align-items-center gap-2">
                        <i className="pi pi-file-pdf text-red-500 text-xl"></i>
                        <span className="font-bold">Letter Preview</span>
                    </div>
                } 
                visible={previewVisible} 
                style={{ width: '90vw', height: '90vh', maxWidth: '1000px' }} 
                maximizable
                onHide={() => setPreviewVisible(false)}
                contentClassName="p-0 overflow-hidden surface-ground"
            >
                {pdfBase64 && (
                    <EmbedPDF data={pdfBase64} fileName="preview.pdf" className="h-full w-full" />
                )}
            </Dialog>
        </div>
    );
};
